services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
    volumes:
      - postgresql_data:/bitnami/postgresql
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: 'host'

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami

  airflow-worker:
    image: bitnami/airflow-worker:latest
    volumes:
      - ../../docker/scripts/mega_sena.py:/opt/bitnami/airflow/dags/mega_sena.py:rw
      - ../../data/base_mega_sena.csv:/data/base_mega_sena.csv:rw
      - ../../resultado:/resultado:rw
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=yes

  airflow-scheduler:
    image: bitnami/airflow-scheduler:latest
    volumes:
      - ../../docker/scripts/mega_sena.py:/opt/bitnami/airflow/dags/mega_sena.py:rw
      - ../../data/base_mega_sena.csv:/data/base_mega_sena.csv:rw
      - ../../resultado:/resultado:rw
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=yes

  airflow:
    image: bitnami/airflow:latest
    volumes:
      - ../../docker/scripts/mega_sena.py:/opt/bitnami/airflow/dags/mega_sena.py:rw
      - ../../data/base_mega_sena.csv:/data/base_mega_sena.csv:rw
      - ../../resultado:/resultado:rw
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_USERNAME=user
      - AIRFLOW_EMAIL=user@example.com
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: 'host'

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local