# https://github.com/marketplace/actions/secret-scanning-custom-action
on:
  push:
  workflow_dispatch:
  
name: Find Secrets
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Secret Scanning Test Suite
        uses: advanced-security/secret-scanning-tools@v1