on:
  push:
  workflow_dispatch:

jobs:
  soos-sca-analysis:
    name: SOOS SCA Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v2
      with:
        project_name: "Sorteios Mega Sena"
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}