name: "SOOS DAST Scan"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  soos_sast:
    name: SOOS SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SOOS SAST
        uses: soos-io/soos-sast-github-action@v1.0.1
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "Mega Sena"
