name: SOOS SAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  soos_sast_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SOOS SAST GitHub Action
        uses: soos-io/soos-sast-github-action@v1.0.1
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "SAST - Mega Sena"
          source_code_path: "./Sorteios_mega_sena"  # Verifique se este caminho está correto
          log_level: "DEBUG"